version: '3.4'

services:
  su-zookeeper:
    image: confluentinc/cp-zookeeper:7.2.0
    container_name: su-zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2183
      ZOOKEEPER_TICK_TIME: 2000

  su-broker:
    image: confluentinc/cp-kafka:7.2.0
    container_name: su-broker
    restart: always
    ports:
    # To learn about configuring Kafka for access across networks see
    # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9192:9192"
    depends_on:
      - su-zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'su-zookeeper:2183'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://su-broker:9192,PLAINTEXT_INTERNAL://su-broker:29192
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  file_server:
    image: file_server
    build:
      context: .
      dockerfile: ./Dockerfile.file_server    
    volumes:
      - ./file_server/data/:/file_server/data
    ports:
      - "5001:5001"

  monitor:
    image: monitor
    build:
      context: .
      dockerfile: ./Dockerfile.monitor
    depends_on:
      - su-broker

  downloader:
    image: downloader
    build:
      context: .
      dockerfile: ./Dockerfile.downloader    
    depends_on:
      - file_server
      - su-broker

  security_events_logger:
    image: security_events_logger
    build:
      context: .
      dockerfile: ./Dockerfile.security_events_logger
    depends_on:
      - su-broker


  storage:
    image: storage
    build:
      context: .
      dockerfile: ./Dockerfile.storage
    depends_on:
      - su-broker

  verifier:
    image: verifier
    build:
      context: .
      dockerfile: ./Dockerfile.verifier
    depends_on:
      - su-broker
      - storage

  manager:
    image: manager
    build:
      context: .
      dockerfile: ./Dockerfile.manager
    depends_on:
      - su-broker      
      # - monitor
      # - downloader
      # - verifier
      # - storage
      # - app_with_updater
    ports:
      - "5002:5002"

  data_input:
    image: data_input
    build:
      context: .
      dockerfile: ./Dockerfile.data_input
    depends_on:
      - su-broker
    environment:
      - DATA_INPUT_API_PORT=6000
    ports:
      - "6000:6000"

  data_processor:
    image: data_processor
    build:
      context: .
      dockerfile: ./Dockerfile.data_processor
    depends_on:
      - su-broker    

  data_output:
    image: data_output
    build:
      context: .
      dockerfile: ./Dockerfile.data_output
    depends_on:
      - su-broker
    environment:
      - DATA_OUTPUT_API_PORT=6001
    ports:
      - "6001:6001"

  fake_service:
      image: fake_service
      container_name: fake_service
      restart: always
      build:
        context: .
        dockerfile: ./Dockerfile.fake_service
      depends_on:
        - monitor
        - su-broker
      ports:
        - "6100:6100"
      environment:
        DATA_INPUT_API_URL: "http://cm-hmi_m_be:6001"
